name: Build and Publish Utility Tools


on:
  push:
    paths:
      - '.github/workflows/ci.yaml'   # Trigger when ci.yaml is modified
      - 'Makefile'                    # Trigger when Makefile is modified
      - 'src/**'                      # Trigger when any file in the src directory is modified
  workflow_dispatch: 

jobs:
  build_and_push_artifactory:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            db_query:
              - 'src/db_query/**'
            vault_auth:
              - 'src/vault_auth/**'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      # - name: Set matrix for changed tools
      #   id: set-matrix
      #   run: |
      #     TOOLS=""
      #     if [ ${{ steps.changes.outputs.db_query }} == 'true' ]; then TOOLS="${TOOLS} db_query"; fi
      #     if [ ${{ steps.changes.outputs.vault_auth }} == 'true' ]; then TOOLS="${TOOLS} vault_auth"; fi
      #     if [ ${{ steps.changes.outputs.opsgenie_client }} == 'true' ]; then TOOLS="${TOOLS} opsgenie_client"; fi
      #     echo "::set-output name=matrix::{\"tool\": [${TOOLS}]}"
      #     echo $TOOLS
        
      # - name: Get version from setup.py
      #   id: get-version
      #   run: |
      #     VERSION=$(grep -Po '(?<=version=")[^"]*' src/${{ matrix.tool }}/setup.py)
      #     echo "::set-output name=version::$VERSION"

      - if: steps.changes.outputs.vault_auth == 'true'
        env:
          TWINE_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.ARTIFACTORY_API_KEY }}
        run: |
          VERSION=$(sed -n 's/^ *version *= *["'\'']\([^"'\'']*\)["'\''].*$/\1/p' src/vault_auth/setup.py)
          echo "::set-output name=version::$VERSION"
          make package target='vault_auth' build_number=${{ steps.get-version.outputs.version }}
          make publish target='vault_auth' build_number=${{ steps.get-version.outputs.version }} url=${{ secrets.ARTIFACTORY_URL }}



      - if: steps.changes.outputs.db_query == 'true'
        env:
          TWINE_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.ARTIFACTORY_API_KEY }}
        run: |
          VERSION=$(sed -n 's/^ *version *= *["'\'']\([^"'\'']*\)["'\''].*$/\1/p' src/db_query/setup.py)
          make package target='db_query' build_number=$VERSION
          make publish target='db_query' build_number=$VERSION url=${{ secrets.ARTIFACTORY_URL }}


# name: shared_tools_build
# run-name: Build number 1.0.${{ github.run_number }}

# on:   
#   workflow_dispatch:      

# jobs:
#   build_and_push_artifactory:
#       name: Build
#       runs-on: ubuntu-latest
#       strategy:
#         fail-fast: false
#         matrix:
#           package:
#             - vault
  
#       steps:
#         - uses: actions/checkout@v3
  
#         - name: Setup Python
#           uses: actions/setup-python@v2
#           with:
#             python-version: "3.12"
  
#         - name: Install dependencies  
#           run: |
#             cd ${{ matrix.package }}
#             python -m pip install --upgrade pip
#             pip install setuptools wheel twine
#         - name: Build the package
#           run: |
#             cd ${{ matrix.package }}
#             python setup.py sdist bdist_wheel
#         - name: Publish to JFrog Artifactory
#           env:
#             TWINE_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
#             TWINE_PASSWORD: ${{ secrets.ARTIFACTORY_API_KEY }}
#           run: |
#             cd ${{ matrix.package }}
#             twine upload --repository-url ${{ secrets.ARTIFACTORY_URL}} \
#             dist/*
#         - name: Clean up build artifacts
#           run: |
#             cd ${{ matrix.package }}
#             rm -rf dist build *.egg-info
#############################

# name: shared_tools_build
# run-name: Build number 1.0.${{ github.run_number }}

# on:   
#   workflow_dispatch:      

# jobs:
#   build_and_push_artifactory:
#       name: Build
#       runs-on: ubuntu-latest
#       strategy:
#         fail-fast: false
#         matrix:
#           package:
#             - vaultt
  
#       steps:
#         - uses: actions/checkout@v3
  
#         - name: Setup Python
#           uses: actions/setup-python@v2
#           with:
#             python-version: "3.12"

#         - name: Setup JFrog CLI
#           uses: jfrog/setup-jfrog-cli@v3
#           env:  
#             JF_URL: ${{ secrets.ARTIFACTORY_URL }}
#             JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_PASSWORD }}

#         - name: Set CLI Config
#           run: |
#             cd ${{ matrix.package }}
#             jf pip-config --global=true --repo-resolve=python-pypi
#             jf pip install .

#         - name: Install dependencies  
#           run: |
#             cd ${{ matrix.package }}
#             python -m pip install --upgrade pip
#             pip install poetry
#         - name: Build the package
#           run: |
#             cd ${{ matrix.package }}
#             python -m poetry build
#             jf rt upload dist/ python-pypi/

#         # - name: Publish to JFrog Artifactory
#         #   env:
#         #     ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
#         #     ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
#         #   run: |
#         #     cd ${{ matrix.package }}
#         #     poetry source add --priority=supplemental jfrog ${{ secrets.ARTIFACTORY_URL }}
#         #     poetry config http-basic.jfrog $ARTIFACTORY_USERNAME $ARTIFACTORY_PASSWORD
#         #     python -m poetry publish
#         # - name: Clean up build artifacts
#         #   run: |
#         #     cd ${{ matrix.package }}
#         #     rm -rf dist build *.egg-info



         
#       #  - name: Publish Build info With JFrog CLI
#       #    run: |
#       #     # Collect environment variables for the build
#       #     jf rt build-collect-env
#       #     # Collect VCS details from git and add them to the build
#       #     jf rt build-add-git
#       #     # Publish build info
#       #     jf rt build-publish
  
#       #   # - name: Install dependencies  
#         #   run: |
#         #     cd ${{ matrix.package }}
#         #     python -m pip install --upgrade pip
#         #     pip install setuptools wheel twine
#         # - name: Build the package
#         #   run: |
#         #     cd ${{ matrix.package }}
#         #     python setup.py sdist bdist_wheel
#         # - name: Publish to JFrog Artifactory
#         #   env:
#         #     TWINE_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
#         #     TWINE_PASSWORD: ${{ secrets.ARTIFACTORY_API_KEY }}
#         #   run: |
#         #     cd ${{ matrix.package }}
#         #     ls dist/
#         #     twine upload --repository-url ${{ secrets.ARTIFACTORY_URL}} \
#         #     dist/*
#         # - name: Clean up build artifacts
#         #   run: |
#         #     cd ${{ matrix.package }}
#         #     rm -rf dist build *.egg-info