name: depends
run-name: Build number 1.0.${{ github.run_number }}

on:   
  workflow_dispatch:      

jobs:
  build_and_push_artifactory:
      name: Build
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
  
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: "3.12"
  

        - name: Install dependencies  
          run: |
            export ARTIFACTORY_USERNAME=ibraim.rakhimdzhanov@gmail.com
            export ARTIFACTORY_URL='testingibraimjfrog.jfrog.io/artifactory/api/pypi/python-pypi-local/simple'
            export ARTIFACTORY_PASSWORD=${{ secrets.ARTIFACTORY_PASSWORD}}
            mkdir -p ~/.pip
            echo "[global]" > ~/.pip/pip.conf
            echo "index-url = https://${ARTIFACTORY_USERNAME}:${ARTIFACTORY_PASSWORD}@${ARTIFACTORY_URL}" >> ~/.pip/pip.conf
            python -m pip install --upgrade pip 
            python3 -m pip install --target ./package -r requirements.txt
            ls ./package


name: shared_tools_build
run-name: Build number 1.0.${{ github.run_number }}

on:   
  workflow_dispatch:      

jobs:
  build_and_push_artifactory:
      name: Build
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          package:
            - vault
  
      steps:
        - uses: actions/checkout@v3
  
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: "3.12"
  
        - name: Install dependencies  
          run: |
            cd ${{ matrix.package }}
            python -m pip install --upgrade pip
            pip install setuptools wheel twine
        - name: Build the package
          run: |
            cd ${{ matrix.package }}
            python setup.py sdist bdist_wheel
        - name: Publish to JFrog Artifactory
          env:
            TWINE_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
            TWINE_PASSWORD: ${{ secrets.ARTIFACTORY_API_KEY }}
          run: |
            cd ${{ matrix.package }}
            twine upload --repository-url ${{ secrets.ARTIFACTORY_URL}} \
            dist/*
        - name: Clean up build artifacts
          run: |
            cd ${{ matrix.package }}
            rm -rf dist build *.egg-info